version: '3'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=app
volumes:
  db_data:
